# Generated by Django 5.2.7 on 2025-10-17 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='entregables',
            field=models.TextField(blank=True, null=True),
        ),
    ]
